### ISSUE TITLE
Return status of test requests

### ISSUE THREAD

**Issue by shivaco** [DiscordBotList/issues#400] opened 2020-07-23 09:41 UTC
#### Suggestion

When pressing the `Test` button on a bot's Edit page to send a test vote request, add a small panel that displays the returned request data (status code, request body, headers, etc.)

Example below:
![Example](https://i.imgur.com/3PEJ9Ji.png)

**Comment by tonkku107** [comment] 2020-07-23 10:14
Duplicate of #51

**Closed by tonkku107** 2020-07-23 10:14 UTC
Labels: DBL, Enhancement
