### ISSUE TITLE
Allow redirects on vote pages

### ISSUE THREAD

**Issue by tilda** [DiscordBotList/issues#116] opened 2018-08-10 07:00 UTC
#### Suggestion

I want to be able to redirect my user back to my bot site after they vote.

Example:
User A clicks on a button (on my site) to vote for my bot.
User A clicks to go back to my bot. (And finds that they get redirected to my bot page instead. How disappointing.)

With this change, I should be able to set a redirect URL on the vote page, such as:

`https://discordbots.org/bot/<bot id>/vote?redirect_url=https://a-bot.website/previous-page`.

#### Applicable Links or Attachments

N/A.

**Comment by tonkku107** [comment] 2018-08-10 08:15
Duplicate of #20

**Closed by tonkku107** 2018-08-10 08:15 UTC
