### ISSUE TITLE
Can't add exactly 3 bots to server listing

### ISSUE THREAD

**Issue by braindigitalis** [DiscordBotList/issues#359] opened 2020-02-04 12:45 UTC
When selecting bots to add to a server, i can't add the number of bots i want to add. The limit seems to be at odds with the check server-side.

#### Expected Behavior

If I tick exactly 3 bots in my server listing they should be listed on the server details.

![image](https://user-images.githubusercontent.com/1556794/73746168-8b659b80-474c-11ea-9190-3cda3ddd167c.png)

#### Observed Behavior

Ticking 3 bots presents me with an error saying i can only tick three or less.

![image](https://user-images.githubusercontent.com/1556794/73746012-33c73000-474c-11ea-9f51-4e8f1cd04c6a.png)

**Comment by tonkku107** [comment] 2020-02-04 12:52
Duplicate of #50

**Closed by tonkku107** 2020-02-04 12:52 UTC
