### ISSUE TITLE
Have the 24 hour voting system reset a little before 24 hours

### ISSUE THREAD

**Issue by jtsshieh** [DiscordBotList/issues#25] opened 2018-05-08 01:12 UTC
#### Suggestion

Instead of exactly 24 hours, you could have the cooldown being 23 or something around this number. Every day, the time of which the user votes will be pushed back a certain amount of seconds, minutes, or even hours. No one (except a bot or very good clickers or people with good luck) can click the vote button exactly when the 24-hour cooldown ends. Therefore, a shorter cooldown will allow it to be not pushed back or even brought forward a bit.

#### Applicable Links or Attachments

*none*

**Comment by zBlakee** [comment] 2018-06-14 13:32
This is a duplicate of #23.

**Closed by zBlakee** 2018-06-14 13:32 UTC
Labels: DBL, enhancement
