### ISSUE TITLE
Long gone bot still shown on profile as featured but can't unselect/remove/update it off 

### ISSUE THREAD

**Issue by Tommyfoxy2** [DiscordBotList/issues#164] opened 2018-10-03 05:24 UTC
#### Expected Behavior

Our listing on DSL shows Mee6 featured, Mee6 has been long gone and I've updated the listing several times trying different things but It will not go away. 

#### Observed Behavior

Our listing on DSL shows Mee6 featured, Mee6 has been long gone and I've updated the listing several times trying different things but It will not go away. Additionally when I try to select 3 bots in the editor it says I can't have more than 3 but Mee6 isn't listed anywhere.

#### Applicable Links or Attachments

![ServerListing](https://i.imgur.com/8LbLAAs.png)
![Editor](https://i.imgur.com/1Whwi12.png)
![Error](https://i.imgur.com/SNslhhm.png)
Above is a result of trying to set 3 bots featured.
[Link to Listing](https://discordbots.org/servers/414234792121597953)

#### Steps to Reproduce

1. https://discordbots.org/servers/414234792121597953/edit
2. Open the editor
3. Try and select 3 bots to be featured. 

#### Web Browser and Version

Google Chrome - Version 69.0.3497.100 (Official Build) (64-bit)

#### Operating System and Version

Windows 7 7601

#### Additional Information/Comments

Sorry for the badly worded title, couldn't figure out a good way to summarize it

**Comment by tonkku107** [comment] 2018-10-03 06:46
Duplicate of #50

**Closed** 2018-10-03 06:47 UTC
Labels: DSL, bug, duplicate
