### ISSUE TITLE
Color for Headers 2+ (Markdown) is white, and doesn't allow text to be seen.

### ISSUE THREAD

**Issue by thehydrogen** [DiscordBotList/issues#336] opened 2019-10-11 19:34 UTC
#### Expected Behavior

Header color is the regular text color which is used for regular text, not the color of the background (white)

#### Observed Behavior

The header color is the color of the background (white) which does not allow the text to be seen.

#### Applicable Links or Attachments

Image of example bot page: (was highlited to show text)
![Image](https://i.thehydrogen.xyz/view/357911279312306176/EA-zp1WVXL.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Open a bot page which uses Markdown headers

#### Web Browser and Version

Google Chrome 77.0.3865.90 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 LTSB

#### Screen Resolution

1920x1080

#### Additional Information/Comments

This might be browser-specific, haven't checked.

**Comment by tonkku107** [comment] 2019-10-11 21:41
Duplicate of #69

**Closed by tonkku107** 2019-10-11 21:41 UTC
