### ISSUE TITLE
Vimeo authorization

### ISSUE THREAD

**Issue by SamSanai** [DiscordBotList/issues#304] opened 2019-07-07 22:01 UTC
#### Suggestion

Save the option when someone ticks the box so that they don't have to do it over and over again every time they edit the bot.

#### Applicable Links or Attachments

![This](https://i.imgur.com/fhC8ock.png)

**Comment by tonkku107** [comment] 2019-07-07 22:59
Duplicate of #101

**Closed by tonkku107** 2019-07-07 22:59 UTC
