### ISSUE TITLE
Change the "Join Discord" to "Join DBL Discord"

### ISSUE THREAD

**Issue by Otiazu** [DiscordBotList/issues#408] opened 2020-08-07 23:59 UTC
#### Suggestion

-It can prevent people from avoiding server confusion, because I have seen many times in the "support" channel that there are many people asking for "Invite Manager" bot, and changing the "Join Discord" to "Join DBL" server can prevent it from following going

by Asterki#0001

**Comment by MahMouDAGYT** [comment] 2020-08-08 00:03
Not a good sug but okay 
I agree .-.

**Comment by shivaco** [comment] 2020-08-08 00:05
Possibly rename it to "Join top.gg server" instead to avoid confusion?

**Comment by tonkku107** [comment] 2020-08-08 06:03
Duplicate of #228

**Closed by tonkku107** 2020-08-08 06:03 UTC
