### ISSUE TITLE
"Github Repository" on Bot Pages Should be Renamed to be Agnostic

### ISSUE THREAD

**Issue by SethiPandi** [DiscordBotList/issues#394] opened 2020-06-26 03:42 UTC
#### Suggestion
I think the `Github Repository` link showed on bot pages should be renamed.

![image](https://user-images.githubusercontent.com/22801583/85817482-6232bf80-b76e-11ea-8e4a-3110c2134086.png)

GitHub isn't the only place where code can be hosted, and git itself is not the only version control system existing, for example there is also Mercurial and Subversion (SVN).  
(Granted I'd be surprised if anyone making a Discord bot wasn't also using Git.)

This looks a bit off for users of [GitLab](https://gitlab.com/), [Bitbucket](https://bitbucket.org/), [Google Cloud Source Repositories](https://cloud.google.com/source-repositories/), or whatever else people want to use as their preferred Git repository host, I'm personally a GitLab user myself.

I believe this should ideally be called something related to `VCS` / `Version Control System`:
* VCS Repository
* Version Control Repository
* Version Control
* Version Control System
* VCS URL

Alternative relating to `Source Code` instead, for example:
* Source Code
* Code
* Code Repository

**Comment by tonkku107** [comment] 2020-06-26 08:12
Duplicate of #177

**Closed by tonkku107** 2020-06-26 08:12 UTC
Labels: DBL, Enhancement
