### ISSUE TITLE
Server doesn't show up on profile 

### ISSUE THREAD

**Issue by Jeija1208** [DiscordBotList/issues#249] opened 2019-01-12 16:04 UTC
#### Expected Behavior

Add the bot and then see it in the server list when you click on your profile (Server: Exploration of hypno)
#### Observed Behavior

Bot has joined but no entry is there 

#### Applicable Links or Attachments

[Image of the server with the bot in it](https://imgur.com/a/x4HfQHb)
[Image of my Server list, the server on the left was only for testing if I could add the bot to other servers](https://imgur.com/a/io7Ak1A)

#### Steps to Reproduce

1. Open Discordbots.org
2. Add the bot

#### Web Browser and Version

Opera Version: 57.0.3098.116

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

The bot was already added one time on the 11/08/2018 but for what i know we never did a server listing for it. I kicked the bot yesterday with the hope it would fix but I can still not see the listing.

**Comment by tonkku107** [comment] 2019-01-12 16:35
Duplicate of #218

**Closed by tonkku107** 2019-01-12 16:35 UTC
