### ISSUE TITLE
This bug has existed for nearly 2 years

### ISSUE THREAD

**Issue by steven4547466** [DiscordBotList/issues#361] opened 2020-03-05 22:43 UTC
https://github.com/DiscordBotList/issues/issues/7

I would follow the format if it wasn't already made and remained the same

Here's the cause

![kc2gfw_3012 1](https://user-images.githubusercontent.com/23726534/76032922-f3a0cc00-5f08-11ea-9728-9e64190ca23d.png) 

![af1kh_3013 1](https://user-images.githubusercontent.com/23726534/76032933-fdc2ca80-5f08-11ea-8e8f-172da18df624.png)

![b1w04e_3010 1](https://user-images.githubusercontent.com/23726534/76032950-02877e80-5f09-11ea-97f0-7f00bda505e5.png)

![tjqtiq_3011 1](https://user-images.githubusercontent.com/23726534/76032957-074c3280-5f09-11ea-8fe9-21d90ac2604f.png)

unedited Title and Alt tags.

**Comment by Xignotic84** [comment] 2020-03-06 00:18
Duplicate of #7

**Closed by Xignotic84** 2020-03-06 00:18 UTC
Labels: Bug, DBL

**Comment by steven4547466** [comment] 2020-03-06 01:31
Then fix it please. It's literally such an easy fix.
