### ISSUE TITLE
BOT's limited amount bug

### ISSUE THREAD

**Issue by AgatePvP** [DiscordBotList/issues#289] opened 2019-04-30 02:04 UTC
#### Expected Behavior

I should be able to add 3 BOTs to my server's BOTs

#### Observed Behavior

But it only allows me to add 2 BOTs

#### Applicable Links or Attachments

[Image of the BOTs amount](http://prntscr.com/niielo)
[Image of the error](http://prntscr.com/niieze)

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to your servers list
3. Select a server
4. Click on edit
5. Select 3 BOTs you have on yout server
6. Click "Submit"

#### Web Browser and Version

Chrome 74.0.3729.108

#### Operating System and Version

Windows 10 1803
Home

#### Screen Resolution

1366x768

#### Additional Information/Comments

I don't know what caused it, i just deleted an old server that doesn't exists anymore.

**Comment by Xignotic84** [comment] 2019-04-30 02:13
This seems to sometimes happen if you've kicked a bot that was previously selected to be shown as the top 3 bots and DSL can't read it, I can't seem to replicate the problem.

**Comment by tonkku107** [comment] 2019-04-30 08:03
Duplicate of #50

**Closed by tonkku107** 2019-04-30 08:03 UTC
Labels: DSL, bug
