### ISSUE TITLE
Remove file extension on user page profile pictures

### ISSUE THREAD

**Issue by jpbberry** [DiscordBotList/issues#331] opened 2019-09-25 22:31 UTC
#### Suggestion

Remove the file extension on user pages

- Allow for discord to chose the best format
- This will allow for animated profile pictures 

#### Applicable Links or Attachments

Example: https://images.discordapp.net/avatars/142408079177285632/a_0f8d0c60fc9ba2b825fd957b3c1c8ac1?size=512 still works, without png, and will automatically give the gif version since i have an animated profile picture.

**Comment by Xignotic84** [comment] 2019-10-02 12:23
Duplicate of ##237

**Closed by Xignotic84** 2019-10-02 12:23 UTC
Labels: DBL, Enhancement
