### ISSUE TITLE
Kicking a featured bot set in server settings on DSL doesn't remove the featured bot from the server page

### ISSUE THREAD

**Issue by automaster6968** [DiscordBotList/issues#194] opened 2018-11-02 05:13 UTC
#### Expected Behavior

When kicking a featured bot set in the server settings of the server list, it should remove the featured bot from the server page.

#### Observed Behavior

The featured bot still stays on the server page after kicking. Clicking "Only Update" in the server settings does not help and because of that it won't let me add another featured bot due to max limit reached if you have 3 bots features. So I have to invite that bot, then remove it as featured from server settings, then kick it.

#### Steps to Reproduce

1. Kick a featured bot set on server settings
2. Go to discordbots.org/servers and go to your server page
3. Try to add another featured bot and it will say error max limit reached if you had 3 ticked before, even though one of the bots were kicked.
4. Invite the featured bot, use Only Update, then untick the featured bot
5. Kick it, press Only Update button, then select the third featured bot without any issue

#### Web Browser and Version

Firefox Quantum 63.0.1 (64-bit)

#### Operating System and Version

Windows 10 1809 Build 17763.55

#### Screen Resolution

1680x1050

**Comment by tonkku107** [comment] 2018-11-02 06:38
Duplicate of #50

**Closed by tonkku107** 2018-11-02 06:38 UTC
