### ISSUE TITLE
Server list - Cannot remove FredBoat from "Top Bots In This Server" (Database bug?)

### ISSUE THREAD

**Issue by Purpzie** [DiscordBotList/issues#204] opened 2018-11-11 19:11 UTC
My server no longer has FredBoat ([here's the page](https://discordbots.org/servers/368499635674808331) in case you guys need to debug).

#### Expected Behavior
The "top bots" section only shows blargbot and Rythm.

#### Observed Behavior
It shows blargbot, Rythm, and FredBoat. It won't let me select another bot as well, since it thinks FredBoat is always selected (even though it doesn't show up and I am unable to un-check it).

#### Applicable Links or Attachments
This is what the edit page looks like to me.
![](https://purpzie.is-bad.com/2efefc.png)

#### Steps to Reproduce
I have absolutely no idea how to reproduce this, but see the additional information/comments section to see some of my thoughts on how it *may* have happened.

#### Web Browser and Version

Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 Home x64 v1709

#### Screen Resolution
Two screens, happens on both (to be honest I don't think this has anything to do with the bug, but I'll include it anyways)
1920x1080 for both

#### Additional Information/Comments
I do remember having it displayed before I kicked out FredBoat, and I believe I didn't have the server list bot in my server at the time. Perhaps it just hasn't realized that the bot isn't there anymore for that reason.

**Comment by tonkku107** [comment] 2018-11-11 19:49
Duplicate of #50

**Closed by tonkku107** 2018-11-11 19:49 UTC
