### ISSUE TITLE
Issue with adding bots to a DSL server

### ISSUE THREAD

**Issue by realCmdData** [DiscordBotList/issues#221] opened 2018-12-13 17:28 UTC
#### Expected Behavior

Being able to add up to three bots.

#### Observed Behavior

Unable to save selection of 3 or less selected bots.

#### Applicable Links or Attachments

Link to gif: https://i.imgur.com/vbEBKYx.gif

#### Steps to Reproduce

1. Click edit on an established server with one bot currently selected (Note, previously selected bot still in server)
2. Select one or even two additional bots (Fails even with new bots entirely)
3. Try and safe changes
4. Error

#### Web Browser and Version

Opera Version 56.0.3051.116

#### Operating System and Version

Windows 10 Home 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Server has more than 10 bots, not sure if this is the cause though

**Comment by tonkku107** [comment] 2018-12-13 17:50
Duplicate of #50

**Comment by realCmdData** [comment] 2018-12-13 17:51
None of the bots were kicked though?

**Closed by tonkku107** 2018-12-13 17:50 UTC

**Comment by tonkku107** [comment] 2018-12-13 17:59
You still have "ghost" entries which is essentially the same bug
