### ISSUE TITLE
I keep getting Error 500 when I try to add my server.

### ISSUE THREAD

**Issue by Sweetxner** [DiscordBotList/issues#277] opened 2019-03-10 15:22 UTC
![image](https://user-images.githubusercontent.com/47016961/54087166-c0902080-4326-11e9-8781-71b34c0387a6.png)

Please help I really want to add my server.

**Comment by tonkku107** [comment] 2019-03-10 16:30
Duplicate of #276

**Closed by tonkku107** 2019-03-10 16:30 UTC
