### ISSUE TITLE
Server viewing error

### ISSUE THREAD

**Issue by AdmagTwoXray** [DiscordBotList/issues#150] opened 2018-09-21 16:47 UTC
Example title: Error on profile page
#### Expected Behavior

I expected to see my server on my profile page after adding it to my discord server

#### Observed Behavior

Instead nothing showed up

#### Applicable Links or Attachments

[http://prntscr.com/kx4wwa](http://prntscr.com/kx4wwa)

#### Steps to Reproduce

1. Open Discordbots.org
2. Press "Add Your Server"
3. Invite bot to server
4. Go to profile page

#### Web Browser and Version

Google Chrome Version 69.0.3497.100

#### Operating System and Version

Windows 7

#### Screen Resolution

1920x1080

**Comment by NotWeeb** [comment] 2018-09-28 12:11
Duplicate of #151

**Closed by NotWeeb** 2018-09-28 12:11 UTC
Labels: DSL, bug
