### ISSUE TITLE
Ram Error Bug

### ISSUE THREAD

**Issue by Gametrock** [DiscordBotList/issues#385] opened 2020-05-30 21:40 UTC
#### Expected Behavior

I was searching for a server with a bit quantity of user

#### Observed Behavior

At page 256 the page gives me an error that you can find at https://ibb.co/6wdsjq6 or https://top.gg/servers/list/top?page=256

#### Applicable Links or Attachments

[Image of the Error](https://ibb.co/6wdsjq6)
[The URL where is this bug](https://top.gg/servers/list/top?page=256)

#### Steps to Reproduce

1. Open top.gg
2. Go to page 256
3. You will find an error of Ram

#### Web Browser and Version

Google Chrome 83.0.4103.61

#### Operating System and Version

Windows 10

#### Screen Resolution

1366×768

#### Additional Information/Comments

It might be because I exceeded the Ram limit

**Comment by tonkku107** [comment] 2020-05-30 21:47
Duplicate of #352

**Closed by tonkku107** 2020-05-30 21:48 UTC

**Comment by Gametrock** [comment] 2020-05-30 21:55
Oh, I didn't know that there was an issue already existing
