### ISSUE TITLE
[DSL] rectangle emojis move on hover

### ISSUE THREAD

**Issue by advaith1** [DiscordBotList/issues#86] opened 2018-07-11 04:17 UTC
#### Expected Behavior

when you hover over an emoji that isnt a square, it doesnt move

#### Observed Behavior

it does move

#### Applicable Links or Attachments

![no hover](https://cdn.discordapp.com/attachments/252296452708106240/466455910345342976/466454977024491540.png)
![hover](https://cdn.discordapp.com/attachments/252296452708106240/466455955446562836/466454869348188169.png)

#### Steps to Reproduce

1. go to a server with emojis that arent exactly square images
2. hover over one of those emojis

#### Web Browser and Version

Google Chrome Version 69.0.3486.0 (and earlier versions)

#### Operating System and Version

macOS High Sierra Version 10.13.5 (17F77)

#### Screen Resolution

5120 x 2880

#### Additional Information/Comments

Adding this css to `gifEmote` fixed it
```css
    margin: auto;
    top: 0;
    bottom: 0;
    position: absolute;
```

**Comment by Chewsterchew** [comment] 2018-07-23 22:49
Possible duplicate of https://github.com/DiscordBotList/issues/issues/75

**Comment by Oliyy** [comment] 2018-07-24 01:31
Duplicate of #75

**Closed by Oliyy** 2018-07-24 01:31 UTC
Labels: DSL, bug
