### ISSUE TITLE
Bot editing error.

### ISSUE THREAD

**Issue by IceeMC** [DiscordBotList/issues#36] opened 2018-05-19 05:41 UTC
Error when editing a bot.

#### Expected Behavior

I expected my bot to successfully be edited.

#### Observed Behavior

Instead i got that error ☹️.

#### Applicable Links or Attachments

![Link to error](https://i.imgur.com/etrTLxr.png)
[Link to Bot](https://discordbots.org/bots/383527587768696832)

#### Steps to Reproduce

1. Go to https://discordbots.org
2. Find a bot that you had that was added in 2017 or earlier
3. Click edit on the bot.
4. Edit the bot support server invite link or something else.
5. Click Submit and you should have received that error. 

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Got None.

**Comment by tonkku107** [comment] 2018-05-19 07:03
Duplicate of #34

**Closed by tonkku107** 2018-05-19 07:03 UTC
