### ISSUE TITLE
Vote page bug on dark theme

### ISSUE THREAD

**Issue by NMW03** [DiscordBotList/issues#405] opened 2020-08-05 22:44 UTC
#### Expected Behavior

The whole page should be dark

#### Observed Behavior

Center is white 

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/50991261/89471029-2b4cc200-d78e-11ea-8e3f-5982b305cb73.png)

#### Steps to Reproduce

1. Open top.gg
2. Switch to Dark Theme
3. Click Vote button for any bot

#### Web Browser and Version

Opera 70.0.3728.71

#### Operating System and Version

Windows 10 2004

#### Screen Resolution

1366 x 768 (btw my zoom setting is 75% for top.gg) 

#### Additional Information/Comments
 
None

**Comment by Xignotic84** [comment] 2020-08-06 00:23
Duplicate of #71

**Closed by Xignotic84** 2020-08-06 00:23 UTC
Labels: DBL, Duplicate
