### ISSUE TITLE
Color of description only in dark mode disappears

### ISSUE THREAD

**Issue by CeaserGaming** [DiscordBotList/issues#159] opened 2018-09-30 12:25 UTC
#### Expected Behavior

I expected the color to be white in dark mode.

#### Observed Behavior

Instead it was black so it blended in.

#### Applicable Links or Attachments

[Light Mode](https://i.imgur.com/I2jL8wN.png)
[Dark Mode](https://i.imgur.com/Xpdjoxn.png)

#### Steps to Reproduce

1. Open https://discordbots.org/bot/473173191649394736
2. Switch to dark mode
3. Text disappears

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1600x900

#### Additional Information/Comments

Its something with CSS but I have no clue.

**Comment by tonkku107** [comment] 2018-09-30 17:45
Duplicate of #69

**Closed** 2018-09-30 17:45 UTC
Labels: DBL, bug, duplicate
