### ISSUE TITLE
Mistitled Badge Hover and Mistake in Bot Section

### ISSUE THREAD

**Issue by mets11rap** [DiscordBotList/issues#93] opened 2018-07-17 22:22 UTC
#### Expected Behavior

I expected the "New trending bots" to be new bots and to display "New" when hovering over the new badge.

#### Observed Behavior

Instead, Mee6 was first when he's been around for a while, and hovering over the badge said "Certified Bots"

#### Applicable Links or Attachments

This image shows both problems https://i.imgur.com/QlXPElO.png

#### Web Browser and Version

Google Chrome Latest

#### Operating System and Version

Windows 7 Ultimate

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment] 2018-07-18 13:07
Mee6 is a featured bot and that is a featured spot. For the other issue, that is a duplicate of #7

**Closed by tonkku107** 2018-07-18 13:07 UTC
Labels: DBL, bug
