### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by IskXmr** [DiscordBotList/issues#220] opened 2018-12-13 08:42 UTC
#### Suggestion

You should add next to the " bot awaiting ..." How many bots are in line before you so that you can see things moving through the website and you can get a rough estimate on when you'll be checked

#### Applicable Links or Attachments

![Image of the cat](https://discordbots.org/images/error.jpg)
[Link to the website](https://discordbots.org)

**Comment by tonkku107** [comment] 2018-12-13 09:17
Duplicate of #198

**Closed by tonkku107** 2018-12-13 09:17 UTC
