### ISSUE TITLE
<h2> text is not readable in dark more

### ISSUE THREAD

**Issue by Jekabs123** [DiscordBotList/issues#357] opened 2020-01-28 05:17 UTC
#### Expected Behavior

`<h2>` text to show black

#### Observed Behavior

It's shoving white, but the background is also white

#### Steps to Reproduce

1. Open top.gg
2. Turn on dark mode
3. Find a bot that has <h2> text in its description

#### Web Browser and Version

Google chrome 79

#### Operating System and Version

Windows 10

#### Screen Resolution

1920 * 1080

**Comment by tonkku107** [comment] 2020-01-28 07:29
Duplicate of #69

**Closed by tonkku107** 2020-01-28 07:29 UTC
