### ISSUE TITLE
Feature: Increase Owner limit for bot

### ISSUE THREAD

**Issue by Flam3rboy** [DiscordBotList/issues#395] opened 2020-06-26 19:12 UTC
#### Suggestion

I think the owner limit of three is too low.
I'm making a really large bot with 5 other devs and not all can get listed on the bot page.
Because of: `Too many other owners listed.`
The limit of owners should be increased at least to five.
Thanks!

**Comment by tonkku107** [comment] 2020-06-26 19:56
Duplicate of #129

**Closed by tonkku107** 2020-06-26 19:56 UTC
